"""Auto-generated by STRepoInstall for attachment 'ccstatusline-editor'. Do not hand-edit
-- `strepoinstall update ccstatusline-editor` overwrites it and `strepoinstall remove ccstatusline-editor`
deletes it. Edit the manifest instead: C:/Users/donal/projects/SText/personal_attachments/ccstatusline_editor/sublime_attach.json

Sublime Text auto-loads every top-level .py file directly under Packages/User/
as its own independent plugin module -- this file is proof: nothing imports
it, ST finds and scans it purely by location and extension, the same way it
finds PluginLoader.py. That's what lets this attachment need zero changes to
any other file.
"""

import importlib
import inspect
import sys

import sublime_plugin

_PLUGIN_DIR = 'C:\\Users\\donal\\projects\\SText\\personal_attachments\\ccstatusline_editor'
_PLUGIN_MODULES = ['ccstatusline_editor_launcher']
_modules = []

if _PLUGIN_DIR and _PLUGIN_DIR not in sys.path:
    sys.path.insert(0, _PLUGIN_DIR)

for _mod_name in _PLUGIN_MODULES:
    _mod = importlib.import_module(_mod_name)
    _modules.append(_mod)
    for _cls_name, _cls in inspect.getmembers(_mod, inspect.isclass):
        if _cls.__module__ != _mod.__name__:
            continue  # skip re-exported/imported classes, not ones the module defines
        if issubclass(_cls, (sublime_plugin.Command, sublime_plugin.EventListener)):
            globals()[_cls_name] = _cls


def plugin_loaded():
    for _mod in _modules:
        _hook = getattr(_mod, "plugin_loaded", None)
        if _hook is not None:
            _hook()


def plugin_unloaded():
    for _mod in _modules:
        _hook = getattr(_mod, "plugin_unloaded", None)
        if _hook is not None:
            _hook()
